# -*- coding: utf-8 -*-
"""Email Spam Classification.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1l9dROIs5HqbLOYSGAzvQA7Ug4RJEpSTJ

# **Email Spam Classification**

# **Libraries Importing**
"""

# Import the required libraries
import pandas as pd
import string
import nltk
from nltk.corpus import stopwords
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import MultinomialNB
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, confusion_matrix

"""# **Data Loading and Exploration**"""

# Load the dataset
df = pd.read_csv('spam.csv', encoding='latin-1')

# First few rows of the dataset
df.head()

# Last few rows of the dataset
df.tail()

# Bried information about the dataset
df.info()

# Descriptive statistics of the dataset
df.describe()

# Shape of the dataset
df.shape

# Rows of the dataset
df.index

# Columns of the dataset
df.columns

# Unique attributes of the dataset
df.nunique()

# Data types in the dataset
df.dtypes

"""# **Data Cleaning and Preprocessing**"""

# Download stopwords if not already downloaded
try:
    stopwords.words('english')
except LookupError:
    nltk.download('stopwords')

def clean_text(text):
    """Converts text to lowercase, removes punctuation and stopwords."""
    text = text.lower()
    text = ''.join([char for char in text if char not in string.punctuation])
    words = text.split()
    words = [word for word in words if word not in stopwords.words('english')]
    return ' '.join(words)

# Apply the cleaning function to the 'Message' column
df['Cleaned_Message'] = df['Message'].apply(clean_text)

# Display the first few rows with the new column
display(df[['Message', 'Cleaned_Message']].head())

"""# **Vectorization**"""

# Instantiate TfidfVectorizer
tfidf_vectorizer = TfidfVectorizer()

# Fit and transform the 'Cleaned_Message' column
X = tfidf_vectorizer.fit_transform(df['Cleaned_Message'])

# Display the shape of the resulting matrix
print("Shape of TF-IDF matrix:", X.shape)

"""# **Model Training**"""

# Define features (X) and target (y), as X was already created in the previous step as the TF-IDF matrix
y = df['Category']

# Split the dataset into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.25, random_state=42)

# Print the shapes of the training and testing sets
print("Shape of X_train:", X_train.shape)
print("Shape of X_test:", X_test.shape)
print("Shape of y_train:", y_train.shape)
print("Shape of y_test:", y_test.shape)

"""# **Model Building**"""

# Instantiate Multinomial Naive Bayes model
mnb_model = MultinomialNB()

# Train the model
mnb_model.fit(X_train, y_train)

"""# **Model Evaluation**"""

# Make predictions on the testing data
y_pred = mnb_model.predict(X_test)

# Calculate and print evaluation metrics
accuracy = accuracy_score(y_test, y_pred)
precision = precision_score(y_test, y_pred, pos_label='spam')
recall = recall_score(y_test, y_pred, pos_label='spam')
f1 = f1_score(y_test, y_pred, pos_label='spam')
conf_matrix = confusion_matrix(y_test, y_pred, labels=['ham', 'spam'])

print(f"Accuracy: {accuracy:.4f}")
print(f"Precision: {precision:.4f}")
print(f"Recall: {recall:.4f}")
print(f"F1-Score: {f1:.4f}")
print("Confusion Matrix:")
print(conf_matrix)

