# -*- coding: utf-8 -*-
"""Coffee Shop Sales Analysis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jVy-sD5J_bwngichqKHY2ks8Z0SXsN9D

# **Coffee Shop Sales Analysis**

# **Libraries Importing**
"""

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from statsmodels.tsa.arima.model import ARIMA

"""# **Data Exploration**"""

# Load the dataset
df = pd.read_csv('coffeeshopsales.csv')

# Show the first few rows of the dataset
df.head()

# Show the last few rows of the dataset
df.tail()

# Brief info about the dataset
df.info()

# Descriptive statistics of the dataset
df.describe()

# Rows of the dataset
df.index

# Columns of the dataset
df.columns

# Unique attributes of the dataset
df.nunique()

# Data types in the dataset
df.dtypes

"""# **Data Cleaning**"""

# Identify missing values
df.isnull().sum()

# Identify duplicate values
df.duplicated().sum()

# Convert 'transaction_date' and 'transaction_time' to datetime objects
df['transaction_date'] = pd.to_datetime(df['transaction_date'])
df['transaction_time'] = pd.to_datetime(df['transaction_time']).dt.time

# Check for duplicate rows
duplicates = df.duplicated().sum()
print(f"Number of duplicate rows: {duplicates}")

# Handle duplicate rows if any (dropping them in this case)
if duplicates > 0:
    df.drop_duplicates(inplace=True)
    print(f"Number of rows after dropping duplicates: {len(df)}")

# Verify data types
print(df.info())

"""**Reasoning**:
Check for inconsistencies in categorical columns.


"""

# Check unique values in categorical columns
categorical_cols = ['store_location', 'product_category', 'product_type', 'product_detail']
for col in categorical_cols:
    print(f"Unique values in '{col}':")
    print(df[col].unique())
    print("-" * 30)

"""# **Analysis Preparation**

"""

# Create sale_price column
df['sale_price'] = df['transaction_qty'] * df['unit_price']

# Convert transaction_date to datetime objects if not already
df['transaction_date'] = pd.to_datetime(df['transaction_date'])

# Extract day of the week and month
df['day_of_week'] = df['transaction_date'].dt.day_name()
df['month'] = df['transaction_date'].dt.month_name()

# Calculate total sales for each product_detail
total_sales_per_product = df.groupby('product_detail')['sale_price'].sum()

# Calculate total quantity sold for each product_detail
total_quantity_sold_per_product = df.groupby('product_detail')['transaction_qty'].sum()

display(df.head())
display(total_sales_per_product.head())
display(total_quantity_sold_per_product.head())

"""# **Profit / Loss Analysis**

"""

# Assume a cost percentage (e.g., 40%)
cost_percentage = 0.40

# Calculate the cost of each transaction
df['cost'] = df['unit_price'] * cost_percentage * df['transaction_qty']

# Calculate the profit for each transaction
df['profit'] = df['sale_price'] - df['cost']

# Calculate the total profit for each product detail
total_profit_per_product = df.groupby('product_detail')['profit'].sum()

# Sort products by total profit in descending order
top_10_profitable_products = total_profit_per_product.sort_values(ascending=False).head(10)

# Sort products by total profit in ascending order
least_profitable_products = total_profit_per_product.sort_values(ascending=True).head(10)

# Display the top 10 most profitable products
print("Top 10 Most Profitable Products:")
display(top_10_profitable_products)

# Display the 10 least profitable products
print("\n10 Least Profitable Products:")
display(least_profitable_products)

# Select top 20 products by profit for visualization
top_20_profitable_products = total_profit_per_product.sort_values(ascending=False).head(20)

# Get the corresponding sales for the top 20 profitable products
top_20_sales = total_sales_per_product.loc[top_20_profitable_products.index]

# Create a DataFrame for plotting
plot_df = pd.DataFrame({
    'product_detail': top_20_profitable_products.index,
    'profit': top_20_profitable_products.values,
    'sales': top_20_sales.values
})

# Melt the DataFrame for easier plotting with seaborn
melted_plot_df = plot_df.melt(id_vars='product_detail', var_name='metric', value_name='amount')

# Plotting total sales and profit for the top 20 products
plt.figure(figsize=(15, 8))
sns.barplot(x='product_detail', y='amount', hue='metric', data=melted_plot_df)
plt.xticks(rotation=90)
plt.title('Total Sales and Profit for Top 20 Profitable Products')
plt.xlabel('Product Detail')
plt.ylabel('Amount')
plt.tight_layout()
plt.show()

# Calculate profit margin for each transaction
df['profit_margin'] = df['profit'] / df['sale_price']

# Visualize the distribution of profit margins
plt.figure(figsize=(10, 6))
sns.histplot(df['profit_margin'], bins=20, kde=True)
plt.title('Distribution of Profit Margins')
plt.xlabel('Profit Margin')
plt.ylabel('Frequency')
plt.show()

"""# **Profit Increase Prediction (If Applicable)**"""

# Group by transaction_date and product_detail and sum the profit
daily_profit_per_product = df.groupby(['transaction_date', 'product_detail'])['profit'].sum()

# Unstack the resulting dataframe
daily_profit_per_product_unstacked = daily_profit_per_product.unstack()

# Fill any missing values with 0
daily_profit_per_product_unstacked = daily_profit_per_product_unstacked.fillna(0)

display(daily_profit_per_product_unstacked.head())

# Select top 5 most profitable products
top_5_products = top_10_profitable_products.head(5).index.tolist()

# Select top 5 least profitable products
least_5_products = least_profitable_products.head(5).index.tolist()

# Combine the lists of products
selected_products = top_5_products + least_5_products

# Create a dictionary to store time series data for each selected product
time_series_data = {}

# For each selected product, prepare the time series data
for product in selected_products:
    if product in daily_profit_per_product_unstacked.columns:
        time_series_data[product] = daily_profit_per_product_unstacked[product]

# Display the first few rows of the time series data for the first selected product as an example
if time_series_data:
    first_product = list(time_series_data.keys())[0]
    print(f"Time series data for {first_product}:")
    display(time_series_data[first_product].head())
else:
    print("No selected products found in the daily profit data.")

# Create a dictionary to store fitted models
fitted_models = {}

# Fit an ARIMA model for each selected product
for product, data in time_series_data.items():
    try:
        # Use a simple ARIMA(5,1,0) model as a starting point
        model = ARIMA(data, order=(5, 1, 0))
        model_fit = model.fit()
        fitted_models[product] = model_fit
        print(f"ARIMA model fitted successfully for {product}")
        # Display model summary for the first fitted model as an example
        if len(fitted_models) == 1:
            print(model_fit.summary())
    except Exception as e:
        print(f"Could not fit ARIMA model for {product}: {e}")

# Provide recommendations based on profitability analysis and model insights

print("Recommendations for Increasing Profit Margins:")

# Recommendations based on profitability analysis
print("\nBased on the profitability analysis:")
print("- Focus marketing and sales efforts on the top 5 most profitable products:")
for product in top_5_products:
    print(f"  - {product}")
print("- Analyze the reasons for low profitability in the least profitable products and consider strategies such as:")
for product in least_5_products:
    print(f"  - {product}")
print("    - Optimizing pricing.")
print("    - Reducing production/sourcing costs.")
print("    - Improving marketing or placement.")
print("    - Considering discontinuation if efforts to improve profitability are unsuccessful.")

# Recommendations based on model insights (example based on ARIMA parameters)
print("\nBased on the ARIMA model insights (trends, seasonality):")
print("- For products with positive trend components, consider scaling up production or stocking levels to meet growing demand.")
print("- For products with significant seasonality, align inventory and marketing campaigns with peak seasons.")
print("- Investigate the factors driving any observed trends or seasonal patterns to capitalize on opportunities or mitigate risks.")
print("- Continuously monitor model performance and retrain models as new data becomes available.")

print("\nOverall Recommendations:")
print("- Conduct a detailed cost analysis for each product to identify areas for cost reduction.")
print("- Explore opportunities for price optimization based on market demand and competitor pricing.")
print("- Implement targeted marketing strategies to promote high-margin products.")
print("- Enhance operational efficiency to reduce overhead costs.")

"""# **Loss Mitigation (If Applicable)**"""

# Identify the least profitable products (already available in least_profitable_products)
print("Least Profitable Products:")
display(least_profitable_products)

# Analyze potential contributing factors for each least profitable product
print("\nAnalysis of Factors Contributing to Low Profitability for Least Profitable Products:")

for product in least_profitable_products.index:
    print(f"\nProduct: {product}")

    # Check total profit
    profit = total_profit_per_product.get(product, 0)
    print(f"- Total Profit: {profit:.2f}")

    # Check total sales volume
    sales_volume = total_quantity_sold_per_product.get(product, 0)
    print(f"- Total Quantity Sold: {sales_volume}")

    # Check total sales revenue
    sales_revenue = total_sales_per_product.get(product, 0)
    print(f"- Total Sales Revenue: {sales_revenue:.2f}")

    # Discuss potential factors based on the values
    if sales_volume < total_quantity_sold_per_product.mean():
        print("- Potential Factor: Low sales volume compared to the average product.")
    if profit < 1000: # Example threshold for low profit
         print("- Potential Factor: Relatively low total profit.")

    # Discuss unit price relative to cost (conceptual, as cost_percentage is fixed)
    print("- Note: With a fixed cost percentage, low profit per unit is directly tied to low unit price.")
    print("  A detailed cost analysis would be crucial to understand true cost per unit and profit margin.")


# Propose mitigation strategies for the least profitable products
print("\nProposed Strategies to Mitigate Low Profitability:")
for product in least_profitable_products.index:
    print(f"\nProduct: {product}")
    print("- Price adjustments: Consider slightly increasing the unit price if market conditions allow.")
    print("- Cost reduction: Explore opportunities for reducing sourcing or production costs (requires detailed cost analysis).")
    print("- Marketing and promotion: Implement targeted campaigns to increase awareness and sales volume.")
    print("- Product bundling: Offer bundles with more popular or higher-margin products.")
    print("- Placement: Optimize product placement in stores or on the menu to increase visibility.")
    print("- Discontinuation: If efforts to improve profitability are unsuccessful after a defined period, consider discontinuing the product.")

# Summarize the analysis and proposed mitigation strategies
print("\nSummary:")
print("The analysis identified several products with the lowest total profit. For these products, potential contributing factors include relatively low sales volume and the impact of a fixed cost percentage on products with lower unit prices. Proposed mitigation strategies involve price adjustments, cost reduction exploration, marketing efforts, product bundling or placement, and potential discontinuation if other strategies are ineffective.")